import { prisma } from "@/lib/prisma";
import { complete } from "@/lib/llm";
import { RYVAN_IDENTITY, RYVAN_SERVICES } from "@/cortex/knowledge/ryvan";

/**
 * Hybrid company-fit analysis.
 *
 * Deterministic heuristics (qualificationScore/grade + signals) are computed
 * upstream by the discovery engine; here we ask the local LLM (Ollama) to write
 * the narrative "does this company suit Ryvan, and how" report, grounded in the
 * Ryvan ICP knowledge base. If the LLM is unavailable, we fall back to a
 * templated report so the feature still works without Ollama.
 */

export interface FitReport {
  report: string;
  score: number;
  grade: string;
  generatedBy: "ollama" | "heuristic";
}

/** Concise Ryvan ICP context injected into the LLM system prompt. */
function ryvanContext(): string {
  const services = RYVAN_SERVICES.map(
    (s) =>
      `- ${s.name} (${s.category}): ${s.description}. Ideal for: ${s.idealFor.join(", ")}. Pricing: pilot ${s.pricingRange.pilot}, quarterly ${s.pricingRange.quarterly}.`,
  ).join("\n");
  return [
    `${RYVAN_IDENTITY.name} — ${RYVAN_IDENTITY.tagline}`,
    `Mission: ${RYVAN_IDENTITY.mission}`,
    `Model: ${RYVAN_IDENTITY.model}`,
    `Flagship: ${RYVAN_IDENTITY.flagship}`,
    ``,
    `Services Ryvan sells:`,
    services,
  ].join("\n");
}

export async function generateFitReport(candidateId: string): Promise<FitReport> {
  const candidate = await prisma.companyCandidate.findUnique({
    where: { id: candidateId },
    include: { signals: true },
  });
  if (!candidate) throw new Error("Candidate not found");

  const score = candidate.qualificationScore ?? 0;
  const grade = candidate.qualificationGrade ?? "—";
  const signalList =
    candidate.signals.map((s) => `${s.type}: ${s.value} (${s.importance})`).join("; ") || "none detected";

  const companyBlock = [
    `Company: ${candidate.companyName}`,
    candidate.website ? `Website: ${candidate.website}` : null,
    candidate.industry ? `Industry: ${candidate.industry}` : null,
    candidate.location ? `Location: ${candidate.location}` : null,
    candidate.description ? `About: ${candidate.description}` : null,
    `Signals: ${signalList}`,
    `Heuristic fit score: ${score}/100 (grade ${grade})`,
  ]
    .filter(Boolean)
    .join("\n");

  const system =
    `You are a business-development analyst for Ryvan Technologies. Assess how well a prospect company fits as a CLIENT for Ryvan's services and write a concise, structured markdown report. Ground every claim ONLY in the data provided — do not invent facts, funding, or headcounts. If the data is thin, say so plainly.\n\n` +
    ryvanContext();

  const user =
    `Analyze this prospect and produce a markdown report with exactly these sections:\n\n` +
    `## Fit Summary\n(2-3 sentences: is this a good Ryvan client, and why)\n\n` +
    `## Recommended Ryvan Services\n(which specific services fit and why, tied to the signals)\n\n` +
    `## Opportunity & Pitch Angle\n(the outreach hook)\n\n` +
    `## Risks / Unknowns\n(what we don't yet know about this company)\n\n` +
    `## Suggested Next Step\n(one concrete action)\n\n` +
    `PROSPECT DATA:\n${companyBlock}`;

  const narrative = await complete(system, user, { temperature: 0.4, maxTokens: 900, timeoutMs: 180_000 });

  const generatedBy: FitReport["generatedBy"] = narrative ? "ollama" : "heuristic";
  const report = narrative ?? heuristicReport(candidate.companyName, score, grade, signalList, candidate.website);

  await prisma.companyCandidate.update({
    where: { id: candidateId },
    data: { analysisReport: report, analyzedAt: new Date() },
  });

  return { report, score, grade, generatedBy };
}

/** Deterministic fallback when Ollama is unavailable. */
function heuristicReport(
  name: string,
  score: number,
  grade: string,
  signalList: string,
  website?: string | null,
): string {
  const verdict =
    score >= 60
      ? "a strong fit — worth prioritising for outreach"
      : score >= 40
        ? "a moderate fit — qualify further before investing time"
        : "a weak fit on current signals";
  return [
    `## Fit Summary`,
    `**${name}** scores ${score}/100 (grade ${grade}) against Ryvan's ICP — ${verdict}.`,
    website ? `Website: ${website}` : "",
    ``,
    `## Signals Detected`,
    signalList,
    ``,
    `## Recommended Ryvan Services`,
    `Based on detected signals, likely fits: ${score >= 40 ? "Web & Mobile Development, DevOps & Automation, or QA Automation (RYN)" : "insufficient signal to recommend specific services"}.`,
    ``,
    `## Suggested Next Step`,
    score >= 40 ? "Enrich the company (website intel) and promote to a prospect for outreach." : "De-prioritise or gather more signals before acting.",
    ``,
    `_Generated by heuristic fallback — start Ollama for a full narrative analysis._`,
  ]
    .filter((l) => l !== "")
    .join("\n");
}
